"""The FL API surface (tests/fl_api_surface.json) turned into callable specs.

The JSON is generated by tests/gen_api_surface.py from the official FL Studio API stubs. It is the single source of
truth for what exists (names) and how it is called (arity, keyword names, coarse types). The fakes in
flsim/fakes/ only add behaviour on top of it.
"""
from __future__ import annotations

import inspect
import json
from functools import lru_cache
from pathlib import Path

SURFACE_PATH = Path(__file__).resolve().parents[1] / "fl_api_surface.json"

# Modules that FL provides natively. `midi` and `utils` are plain Python files in FL's Shared/Python/Lib and are
# loaded from the real files (see fakes/pylib.py), so they are not wrapped.
NATIVE_MODULES = (
    "arrangement", "channels", "device", "general", "launchMapPages", "mixer",
    "patterns", "playlist", "plugins", "screen", "transport", "ui",
)
PY_LIB_MODULES = ("midi", "utils")
API_MODULES = NATIVE_MODULES + PY_LIB_MODULES

# Callbacks FL calls in a script (names only). Anything else is not an FL callback.
_NO_DEFAULT = inspect.Parameter.empty


class FuncSpec:
    """Signature + coarse types of one FL API function, with a fast arity/type check."""

    __slots__ = ("module", "name", "qual", "params", "required", "param_types", "positional_only", "keyword_only",
                 "varargs", "varkw", "returns", "signature", "_max_pos", "_typed", "_kwnames")

    def __init__(self, module: str, name: str, raw: dict):
        self.module = module
        self.name = name
        self.qual = "%s.%s" % (module, name)
        self.params = list(raw.get("params", []))
        self.required = int(raw.get("required", 0))
        self.param_types = list(raw.get("param_types", [])) + [""] * len(self.params)
        self.positional_only = set(raw.get("positional_only") or [])
        self.keyword_only = set(raw.get("keyword_only") or [])
        self.varargs = raw.get("varargs")
        self.varkw = raw.get("varkw")
        self.returns = raw.get("returns", "")
        params = []
        for i, p in enumerate(self.params):
            if p in self.positional_only:
                kind = inspect.Parameter.POSITIONAL_ONLY
            elif p in self.keyword_only:
                kind = inspect.Parameter.KEYWORD_ONLY
            else:
                kind = inspect.Parameter.POSITIONAL_OR_KEYWORD
            params.append(inspect.Parameter(p, kind, default=_NO_DEFAULT if i < self.required else None))
        if self.varargs:
            params.insert(len([q for q in params if q.kind is not inspect.Parameter.KEYWORD_ONLY]),
                          inspect.Parameter(self.varargs, inspect.Parameter.VAR_POSITIONAL))
        if self.varkw:
            params.append(inspect.Parameter(self.varkw, inspect.Parameter.VAR_KEYWORD))
        try:
            self.signature = inspect.Signature(params)
        except ValueError:  # ill-ordered defaults in a stub: fall back to a permissive signature
            self.signature = inspect.Signature([
                inspect.Parameter("args", inspect.Parameter.VAR_POSITIONAL),
                inspect.Parameter("kwargs", inspect.Parameter.VAR_KEYWORD)])
        pos = [p for p in self.params if p not in self.keyword_only]
        self._max_pos = None if self.varargs else len(pos)
        self._kwnames = frozenset(p for p in self.params if p not in self.positional_only)
        self._typed = [(i, p, t) for i, (p, t) in enumerate(zip(self.params, self.param_types))
                       if t in _CHECKERS and p not in self.keyword_only]

    def check(self, args: tuple, kwargs: dict, types: bool = True) -> None:
        """Raise TypeError like a native FL function would for a wrong call. Fast path for positional calls."""
        n = len(args)
        if not kwargs:
            if n < self.required or (self._max_pos is not None and n > self._max_pos):
                raise TypeError(self._arity_msg(n))
        else:
            unknown = [k for k in kwargs if k not in self._kwnames and not self.varkw]
            if unknown:
                raise TypeError("%s() got an unexpected keyword argument '%s'" % (self.qual, unknown[0]))
            try:
                self.signature.bind(*args, **kwargs).arguments  # noqa: B018 - bind() raises the right TypeError
            except TypeError as e:
                raise TypeError("%s(): %s" % (self.qual, e)) from None
        if not types:
            return
        for i, p, t in self._typed:
            if i < n:
                v = args[i]
            elif p in kwargs:
                v = kwargs[p]
            else:
                continue
            if not _CHECKERS[t](v):
                raise TypeError("%s() argument '%s' must be %s, not %s" % (self.qual, p, t, type(v).__name__))

    def _arity_msg(self, n: int) -> str:
        hi = "any" if self._max_pos is None else self._max_pos
        return "%s() takes %s..%s positional arguments but %d were given" % (self.qual, self.required, hi, n)


def _is_int(v) -> bool:
    return isinstance(v, int) and not isinstance(v, float)


_CHECKERS = {
    "int": _is_int,
    "float": lambda v: isinstance(v, (int, float)),
    "bool": lambda v: isinstance(v, (bool, int)),
    "str": lambda v: isinstance(v, str),
    "bytes": lambda v: isinstance(v, (bytes, bytearray, memoryview)),
}


@lru_cache(maxsize=1)
def load_surface() -> dict:
    with open(SURFACE_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


@lru_cache(maxsize=None)
def spec(module: str, name: str) -> FuncSpec | None:
    raw = load_surface().get(module, {}).get(name)
    if raw is None or not isinstance(raw, dict) or "params" not in raw:
        return None
    return FuncSpec(module, name, raw)


def function_names(module: str) -> list[str]:
    return sorted(k for k, v in load_surface().get(module, {}).items() if isinstance(v, dict) and "params" in v)


def callback_names() -> list[str]:
    return sorted(load_surface()["callbacks"])


def midi_constants() -> dict:
    """Constants of the real FL midi.py as recorded in the surface (used only when the real file is absent)."""
    c = load_surface().get("constants", {})
    return dict(c.get("midi_fl_real") or c.get("midi") or {})


def is_query(qual: str) -> bool:
    """True for API functions that only read FL state (used to separate 'effects' from queries in traces)."""
    name = qual.rsplit(".", 1)[-1]
    if name.startswith(("get", "is", "has", "can", "find", "check")):
        return True
    return name in _QUERY_NAMES


_QUERY_NAMES = {
    "trackNumber", "trackCount", "channelNumber", "selectedChannel", "channelCount", "patternNumber",
    "patternCount", "patternMax", "currentTime", "length", "dispatchReceiverCount",
}
